### ISSUE TITLE
Option to display and use search box on map

### ISSUE THREAD

**Issue by KrisSiegel** [GoogleWebComponents/google-map#115]
Adding a search box isn't too bad but not exactly straight forward. It seems to me it would fit the polymer convention to add an option (or element? not sure which) to display a functional search box directly on the map.

Thoughts? I need to add one for a current project of mine, if it's desired I'll see if I can incorporate it directly into google-maps.

**Comment by ebidel** [comment]
I don't think this makes sense to add directly to the component. It's easier enough to bind a input to the map or use https://github.com/GoogleWebComponents/google-map/blob/master/google-map-search.html for that purpose

**Comment by supita** [comment]
Actually, the search box on the map only using GoogleWebComponents is kind of tricky, not because of the search box, but to get the results, right now google-map-search just gives you the geocoordinates of the first result in the query, and trims the rest of the info of that first result that the maps api gives you (like the place name, icon, address and so). 

If you want to do a search and show multiple results google-map-search is not your guy, I think the intention with this component was get the info for just one marker. 

Is it going to have the ability to get more than one result? Are you guys planning to have a second component for this? I understand that exposing multiple results is a huge change for the component.

**Comment by ebidel** [comment]
https://github.com/GoogleWebComponents/google-map/issues/16

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you feel strongly about this.
