### ISSUE TITLE
createElement fails for google-map

### ISSUE THREAD

**Issue by derek1906** [GoogleWebComponents/google-map#160]
Placing multiple `<google-map>` in the same document will cause it to throw an error:

>Uncaught TypeError: latitude must be a number

No matter it is created via JavaScript or directly in HTML, it still seems to yield the same result.

**Comment by atotic** [comment]
It usually works. Is there anything specific to your setup making them do that?
Do you have an example?

**Comment by derek1906** [comment]
Here's a [demo](https://github.com/derek1906/google-map-demo) which by only executing `document.createElement("google-map")` will cause the error to show up.

Navigate to `map.html` and in the error message can be seen in the console. Notice in line 71 of `page1.html` there is a pre-placed google-map element. If this element is commented out, then it will not throw an error.

**Comment by atotic** [comment]
I get it. Related to #147

What happens is:
- google-map try to initialize itself when googlemap library is loaded.
- when you create google-map createElement(), that initialization fails because map has not been attached to dom yet.

The reason why first map triggers the bug is:
- library only gets loaded once element is inserted into dom. That's why you would not see the error with a single map.
- first element loads the library
- second element gets 'libraryLoaded' before being attached to dom and dies

It's been on the radar, but we did not see it in the wild. Will fix. Thanks for the report.

**Comment by derek1906** [comment]
Is there any "quick fix" or workaround that I can apply now to avoid this issue? How soon will we see a fix for this issue?

**Comment by atotic** [comment]
There is no workaround. It is not on my slate for the next few days, but it could happen if I get an itch. If you need it by Monday, I'd fork and patch the bug in your own tree. You just need to move map initialization around.

**Comment by derek1906** [comment]
Oh this is not urgent; I'm just curious on when we'll be seeing a patch :)

**Comment by atotic** [comment]
It works on #master right now. Other fixes fixed this as a side-effect.
