### ISSUE TITLE
Controls position 

### ISSUE THREAD

**Issue by Bodhiz** [GoogleWebComponents/google-map#217]
Hi,

I'm trying to move zoom controls position, as it's not an option exposed as a property, I used the available additional-map-options one  but I can't get it to work
Here is my code 

```
<google-map id="gmap" latitude="{{latitude}}" longitude="{{longitude}}" zoom="{{zoom}}" drag-events="true" additional-map-options='{"zoomControlOptions": { "position": google.maps.ControlPosition.TOP_RIGHT}}' on-google-map-ready="_initMap">
```
Am I doing something wrong or is it currently not supported ?

Note : If I try with a "simpler" option like zoomControl turning it to false it works perfectly. 

Thanks.

**Comment by ebidel** [comment]
This is a polymer issue (https://github.com/Polymer/polymer/issues/2609) we'll have to work around.

**Comment by ebidel** [comment]
Actually `JSON.parse('{"zoomControlOptions":{"position":google.maps.ControlPosition.TOP_RIGHT}}')` throws an error. So you won't be able to use `google.maps.ControlPosition.TOP_RIGHT` as a value. I'd recommend setting the `map.additionalMapsOptions` in JS instead of using the declared attribute.

I've added docs: https://github.com/GoogleWebComponents/google-map/commit/d2c1bb65e48722d91a98e56804c659a8cae983ea
